// server.js
const express = require('express');
const multer = require('multer');
const path = require('path');
const fs = require('fs-extra');
const sharp = require('sharp');
const cors = require('cors');
const { spawn } = require('child_process');

const app = express();
const PORT = 3000;

const UPLOAD_DIR = path.join(__dirname, 'public/uploads');
const THUMB_DIR = path.join(__dirname, 'public/thumbnails');

// Ensure upload folders exist
fs.ensureDirSync(UPLOAD_DIR);
`fs.ensureDirSync(THUMB_DIR);`

app.use(cors());
app.use(express.static('public'));
app.use(express.json());



// Configure multer for disk storage
const storage = multer.diskStorage({
    destination: (req, file, cb) => cb(null, UPLOAD_DIR),
    filename: (req, file, cb) => {
        const uniqueName = `${Date.now()}-${file.originalname}`;
        cb(null, uniqueName);
    }
});
const upload = multer({ storage });

// Upload route
app.post('/upload', upload.single('file'), async (req, res) => {
    try {
        if (!req.file) {
            console.error('❌ Upload error: No file received');
            return res.status(400).json({ success: false, message: 'No file received' });
        }

        console.log(`📤 Received file: ${req.file.originalname} (${req.file.size} bytes)`);
        
        // Check for duplicate by original filename
        const originalname = req.file.originalname;
        const existingFiles = await fs.readdir(UPLOAD_DIR);
        
        // Get the uploaded file paths
        const tempPath = req.file.path;
        const filename = req.file.filename; // This is the unique filename generated by multer
        const ext = path.extname(req.file.originalname).toLowerCase();

        // Optional duplicate check - can be enabled/disabled as needed
        let isDuplicate = false;
        for (const existingFile of existingFiles) {
            // Skip the file we just uploaded
            if (existingFile === filename) continue;
            
            // Check if another file with the same original name exists
            // This is useful for preventing duplicate uploads
            if (existingFile.endsWith(originalname) || existingFile === originalname) {
                console.warn(`⚠️ Duplicate detected: ${originalname} already exists as ${existingFile}`);
                isDuplicate = true;
                break;
            }
        }
        
        // If duplicate found, you can either:
        // 1. Return an error (preventing the upload)
        // 2. Continue with the upload (allowing duplicates)
        // 3. Rename the file (adding a suffix like "(1)")
        
        // Option 1: Return an error for duplicates (uncomment if you want to prevent duplicates)
        /*
        if (isDuplicate) {
            // Remove the uploaded file
            await fs.remove(tempPath);
            return res.status(400).json({ 
                success: false, 
                message: 'This file already exists. Please rename it or upload a different file.',
                isDuplicate: true
            });
        }
        */
        
        
        res.json({ 
            success: true, 
            filename: filename,
            originalname: req.file.originalname,
            isDuplicate: isDuplicate // Let the client know if it was a duplicate
        });
    } catch (err) {
        console.error('❌ Upload error:', err);
        res.status(500).json({ 
            success: false, 
            error: err.toString(),
            message: 'File upload failed'
        });
    }
});


// Get file list
app.get('/uploads', async (req, res) => {
    try {
        const filter = req.query.filter || 'all';
        const page = parseInt(req.query.page) || 1;
        const limit = parseInt(req.query.limit) || 26;
        const checkDuplicates = req.query.checkDuplicates === 'true';
        
        const files = await fs.readdir(UPLOAD_DIR);
        
        // Categorize files
        const fileObjects = await Promise.all(files.map(async filename => {
            const filePath = path.join(UPLOAD_DIR, filename);
            const stats = await fs.stat(filePath);
            const ext = path.extname(filename).toLowerCase();
            
            // Determine file type
            let type = 'other';
            if (['.jpg', '.jpeg', '.png', '.gif', '.webp'].includes(ext)) {
                type = 'image';
            } else if (['.mp4', '.webm', '.mov'].includes(ext)) {
                type = 'video';
            }
            
            return {
                filename,
                size: stats.size,
                modified: stats.mtime,
                type
            };
        }));
        
        // Filter files
        let filteredFiles = fileObjects;
        if (filter === 'image') {
            filteredFiles = fileObjects.filter(file => file.type === 'image');
        } else if (filter === 'video') {
            filteredFiles = fileObjects.filter(file => file.type === 'video');
        } else if (filter === 'other') {
            filteredFiles = fileObjects.filter(file => file.type === 'other');
        }
        
        // Count by type
        const counts = {
            images: fileObjects.filter(file => file.type === 'image').length,
            videos: fileObjects.filter(file => file.type === 'video').length,
            others: fileObjects.filter(file => file.type === 'other').length
        };
        counts.all = counts.images + counts.videos + counts.others;
        
        // For duplicate checking, return all files without pagination
        if (checkDuplicates) {
            return res.json({
                files: filteredFiles,
                counts,
                total: filteredFiles.length
            });
        }
        
        // Pagination
        const startIndex = (page - 1) * limit;
        const endIndex = page * limit;
        const paginatedFiles = filteredFiles.slice(startIndex, endIndex);
        
        // Calculate total pages
        const totalFiles = filteredFiles.length;
        const totalPages = Math.ceil(totalFiles / limit);
        
        // Always return a consistent response shape, even if the filtered list is empty
        res.json({
            files: paginatedFiles,
            counts,
            hasMore: endIndex < filteredFiles.length,
            page,
            totalFiles,
            totalPages
        });
    } catch (err) {
        console.error('Error listing files:', err);
        res.status(500).json({ 
            error: 'Failed to list files',
            message: err.message,
            files: [],
            counts: { images: 0, videos: 0, others: 0, all: 0 },
            hasMore: false,
            page: 1,
            totalFiles: 0,
            totalPages: 0
        });
    }
});

// Delete a file
app.delete('/delete/:filename', async (req, res) => {
    try {
        const filename = req.params.filename;
        const filePath = path.join(UPLOAD_DIR, filename);
        const thumbPath = path.join(THUMB_DIR, filename);
        
        // Remove the file
        await fs.remove(filePath);
        
        // Remove thumbnail if it exists
        try {
            await fs.remove(thumbPath);
        } catch (thumbErr) {
            console.warn(`Could not remove thumbnail for ${filename}:`, thumbErr);
            // Continue even if thumbnail deletion fails
        }
        
        // Get updated file counts
        const remainingFiles = await fs.readdir(UPLOAD_DIR);
        
        // Count files by type
        const counts = {
            images: 0,
            videos: 0,
            others: 0
        };
        
        for (const file of remainingFiles) {
            const ext = path.extname(file).toLowerCase();
            if (['.jpg', '.jpeg', '.png', '.gif', '.webp'].includes(ext)) {
                counts.images++;
            } else if (['.mp4', '.webm', '.mov'].includes(ext)) {
                counts.videos++;
            } else {
                counts.others++;
            }
        }
        
        counts.all = counts.images + counts.videos + counts.others;
        
        res.json({ 
            success: true, 
            message: `File ${filename} deleted successfully`,
            counts
        });
    } catch (err) {
        console.error('❌ Delete error:', err);
        res.status(500).json({ 
            success: false, 
            error: err.toString() 
        });
    }
});

// Rename a file
app.post('/rename', async (req, res) => {
    const { oldName, newName } = req.body;
    const oldPath = path.join(UPLOAD_DIR, oldName);
    const newPath = path.join(UPLOAD_DIR, newName);

    await fs.rename(oldPath, newPath);

    const oldThumb = path.join(THUMB_DIR, oldName);
    const newThumb = path.join(THUMB_DIR, newName);
    if (await fs.pathExists(oldThumb)) {
        await fs.rename(oldThumb, newThumb);
    }

    res.json({ success: true });
});

// Start server
app.listen(PORT, () => {
    console.log(`🚀 Server running at http://localhost:${PORT}`);
});
